version: "3"

services:
  db:
    image: mongo:4.2
    restart: always
  web:
    build:
      context: .
    image: nllevin/whelp:1 
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db